const globalData = {
  gold: 24.5,
  btc: 23.8,
  countries: {
    "IT": {'name': 'Italia', 'local': 22.5, 'comment': 'Agroalimentare e manifattura forti', 'source': 'https://www.fao.org/italy'},
    "DE": {'name': 'Germania', 'local': 23.4, 'comment': 'Industria solida, buona filiera interna', 'source': 'https://www.worldbank.org/germany'},
    "CN": {'name': 'Cina', 'local': 25.1, 'comment': 'Produzione interna massiva', 'source': 'https://www.worldbank.org/china'},
    "US": {'name': 'Stati Uniti', 'local': 24.9, 'comment': 'Economia diversificata, energia interna forte', 'source': 'https://www.fao.org/usa'},
    "IN": {'name': 'India', 'local': 23.0, 'comment': 'Settore agricolo esteso, autosufficienza parziale', 'source': 'https://www.fao.org/india'},
    "BR": {'name': 'Brasile', 'local': 22.6, 'comment': 'Potenziale agricolo enorme', 'source': 'https://www.fao.org/brazil'},
    "FR": {'name': 'Francia', 'local': 22.8, 'comment': 'Forte settore agroalimentare', 'source': 'https://www.oecd.org/france'},
    "JP": {'name': 'Giappone', 'local': 21.5, 'comment': 'Alta tecnologia, forte import', 'source': 'https://www.worldbank.org/japan'},
    "RU": {'name': 'Russia', 'local': 23.3, 'comment': 'Materie prime abbondanti', 'source': 'https://www.worldbank.org/russia'},
    "NG": {'name': 'Nigeria', 'local': 20.2, 'comment': 'Economia agricola in crescita', 'source': 'https://www.fao.org/nigeria'},
    "AW": {'name': 'Aruba', 'local': 21.8, 'comment': 'Valutazione sintetica su Aruba', 'source': 'https://example.com/aw'},
    "AF": {'name': 'Afghanistan', 'local': 25.3, 'comment': 'Valutazione sintetica su Afghanistan', 'source': 'https://example.com/af'},
    "AO": {'name': 'Angola', 'local': 18.7, 'comment': 'Valutazione sintetica su Angola', 'source': 'https://example.com/ao'},
    "AI": {'name': 'Anguilla', 'local': 20.8, 'comment': 'Valutazione sintetica su Anguilla', 'source': 'https://example.com/ai'},
    "AX": {'name': 'Åland Islands', 'local': 23.4, 'comment': 'Valutazione sintetica su Åland Islands', 'source': 'https://example.com/ax'},
    "AL": {'name': 'Albania', 'local': 23.7, 'comment': 'Valutazione sintetica su Albania', 'source': 'https://example.com/al'},
    "AD": {'name': 'Andorra', 'local': 26.3, 'comment': 'Valutazione sintetica su Andorra', 'source': 'https://example.com/ad'},
    "AE": {'name': 'United Arab Emirates', 'local': 26.4, 'comment': 'Valutazione sintetica su United Arab Emirates', 'source': 'https://example.com/ae'},
    "AR": {'name': 'Argentina', 'local': 22.3, 'comment': 'Valutazione sintetica su Argentina', 'source': 'https://example.com/ar'},
    "AM": {'name': 'Armenia', 'local': 21.9, 'comment': 'Valutazione sintetica su Armenia', 'source': 'https://example.com/am'},
    "AS": {'name': 'American Samoa', 'local': 21.1, 'comment': 'Valutazione sintetica su American Samoa', 'source': 'https://example.com/as'},
    "AQ": {'name': 'Antarctica', 'local': 21.8, 'comment': 'Valutazione sintetica su Antarctica', 'source': 'https://example.com/aq'},
    "TF": {'name': 'French Southern Territories', 'local': 18.5, 'comment': 'Valutazione sintetica su French Southern Territories', 'source': 'https://example.com/tf'},
    "AG": {'name': 'Antigua and Barbuda', 'local': 24.3, 'comment': 'Valutazione sintetica su Antigua and Barbuda', 'source': 'https://example.com/ag'},
    "AU": {'name': 'Australia', 'local': 19.8, 'comment': 'Valutazione sintetica su Australia', 'source': 'https://example.com/au'},
    "AT": {'name': 'Austria', 'local': 24.8, 'comment': 'Valutazione sintetica su Austria', 'source': 'https://example.com/at'},
    "AZ": {'name': 'Azerbaijan', 'local': 22.8, 'comment': 'Valutazione sintetica su Azerbaijan', 'source': 'https://example.com/az'},
    "BI": {'name': 'Burundi', 'local': 21.9, 'comment': 'Valutazione sintetica su Burundi', 'source': 'https://example.com/bi'},
    "BE": {'name': 'Belgium', 'local': 25.6, 'comment': 'Valutazione sintetica su Belgium', 'source': 'https://example.com/be'},
    "BJ": {'name': 'Benin', 'local': 20.9, 'comment': 'Valutazione sintetica su Benin', 'source': 'https://example.com/bj'},
    "BQ": {'name': 'Bonaire, Sint Eustatius and Saba', 'local': 18.9, 'comment': 'Valutazione sintetica su Bonaire, Sint Eustatius and Saba', 'source': 'https://example.com/bq'},
    "BF": {'name': 'Burkina Faso', 'local': 18.2, 'comment': 'Valutazione sintetica su Burkina Faso', 'source': 'https://example.com/bf'},
    "BD": {'name': 'Bangladesh', 'local': 18.2, 'comment': 'Valutazione sintetica su Bangladesh', 'source': 'https://example.com/bd'},
    "BG": {'name': 'Bulgaria', 'local': 26.1, 'comment': 'Valutazione sintetica su Bulgaria', 'source': 'https://example.com/bg'},
    "BH": {'name': 'Bahrain', 'local': 26.6, 'comment': 'Valutazione sintetica su Bahrain', 'source': 'https://example.com/bh'},
    "BS": {'name': 'Bahamas', 'local': 23.8, 'comment': 'Valutazione sintetica su Bahamas', 'source': 'https://example.com/bs'},
    "BA": {'name': 'Bosnia and Herzegovina', 'local': 24.3, 'comment': 'Valutazione sintetica su Bosnia and Herzegovina', 'source': 'https://example.com/ba'},
    "BL": {'name': 'Saint Barthélemy', 'local': 22.5, 'comment': 'Valutazione sintetica su Saint Barthélemy', 'source': 'https://example.com/bl'},
    "BY": {'name': 'Belarus', 'local': 22.6, 'comment': 'Valutazione sintetica su Belarus', 'source': 'https://example.com/by'},
    "BZ": {'name': 'Belize', 'local': 25.3, 'comment': 'Valutazione sintetica su Belize', 'source': 'https://example.com/bz'},
    "BM": {'name': 'Bermuda', 'local': 18.2, 'comment': 'Valutazione sintetica su Bermuda', 'source': 'https://example.com/bm'},
    "BO": {'name': 'Bolivia, Plurinational State of', 'local': 26.8, 'comment': 'Valutazione sintetica su Bolivia, Plurinational State of', 'source': 'https://example.com/bo'},
    "BB": {'name': 'Barbados', 'local': 19.5, 'comment': 'Valutazione sintetica su Barbados', 'source': 'https://example.com/bb'},
    "BN": {'name': 'Brunei Darussalam', 'local': 24.6, 'comment': 'Valutazione sintetica su Brunei Darussalam', 'source': 'https://example.com/bn'},
    "BT": {'name': 'Bhutan', 'local': 24.8, 'comment': 'Valutazione sintetica su Bhutan', 'source': 'https://example.com/bt'},
    "BV": {'name': 'Bouvet Island', 'local': 18.6, 'comment': 'Valutazione sintetica su Bouvet Island', 'source': 'https://example.com/bv'},
    "BW": {'name': 'Botswana', 'local': 22.8, 'comment': 'Valutazione sintetica su Botswana', 'source': 'https://example.com/bw'},
    "CF": {'name': 'Central African Republic', 'local': 22.3, 'comment': 'Valutazione sintetica su Central African Republic', 'source': 'https://example.com/cf'},
    "CA": {'name': 'Canada', 'local': 24.9, 'comment': 'Valutazione sintetica su Canada', 'source': 'https://example.com/ca'},
    "CC": {'name': 'Cocos (Keeling) Islands', 'local': 20.5, 'comment': 'Valutazione sintetica su Cocos (Keeling) Islands', 'source': 'https://example.com/cc'},
    "CH": {'name': 'Switzerland', 'local': 25.5, 'comment': 'Valutazione sintetica su Switzerland', 'source': 'https://example.com/ch'},
    "CL": {'name': 'Chile', 'local': 24.0, 'comment': 'Valutazione sintetica su Chile', 'source': 'https://example.com/cl'},
    "CI": {'name': "Côte d'Ivoire", 'local': 25.2, 'comment': "Valutazione sintetica su Côte d'Ivoire", 'source': 'https://example.com/ci'},
    "CM": {'name': 'Cameroon', 'local': 24.7, 'comment': 'Valutazione sintetica su Cameroon', 'source': 'https://example.com/cm'},
    "CD": {'name': 'Congo, The Democratic Republic of the', 'local': 22.2, 'comment': 'Valutazione sintetica su Congo, The Democratic Republic of the', 'source': 'https://example.com/cd'},
    "CG": {'name': 'Congo', 'local': 19.2, 'comment': 'Valutazione sintetica su Congo', 'source': 'https://example.com/cg'},
    "CK": {'name': 'Cook Islands', 'local': 23.1, 'comment': 'Valutazione sintetica su Cook Islands', 'source': 'https://example.com/ck'},
    "CO": {'name': 'Colombia', 'local': 23.4, 'comment': 'Valutazione sintetica su Colombia', 'source': 'https://example.com/co'},
    "KM": {'name': 'Comoros', 'local': 23.9, 'comment': 'Valutazione sintetica su Comoros', 'source': 'https://example.com/km'},
    "CV": {'name': 'Cabo Verde', 'local': 24.0, 'comment': 'Valutazione sintetica su Cabo Verde', 'source': 'https://example.com/cv'},
    "CR": {'name': 'Costa Rica', 'local': 19.5, 'comment': 'Valutazione sintetica su Costa Rica', 'source': 'https://example.com/cr'},
    "CU": {'name': 'Cuba', 'local': 24.2, 'comment': 'Valutazione sintetica su Cuba', 'source': 'https://example.com/cu'},
    "CW": {'name': 'Curaçao', 'local': 23.7, 'comment': 'Valutazione sintetica su Curaçao', 'source': 'https://example.com/cw'},
    "CX": {'name': 'Christmas Island', 'local': 23.8, 'comment': 'Valutazione sintetica su Christmas Island', 'source': 'https://example.com/cx'},
    "KY": {'name': 'Cayman Islands', 'local': 22.4, 'comment': 'Valutazione sintetica su Cayman Islands', 'source': 'https://example.com/ky'},
    "CY": {'name': 'Cyprus', 'local': 23.3, 'comment': 'Valutazione sintetica su Cyprus', 'source': 'https://example.com/cy'},
    "CZ": {'name': 'Czechia', 'local': 23.4, 'comment': 'Valutazione sintetica su Czechia', 'source': 'https://example.com/cz'},
    "DJ": {'name': 'Djibouti', 'local': 22.2, 'comment': 'Valutazione sintetica su Djibouti', 'source': 'https://example.com/dj'},
    "DM": {'name': 'Dominica', 'local': 20.2, 'comment': 'Valutazione sintetica su Dominica', 'source': 'https://example.com/dm'},
    "DK": {'name': 'Denmark', 'local': 23.9, 'comment': 'Valutazione sintetica su Denmark', 'source': 'https://example.com/dk'},
    "DO": {'name': 'Dominican Republic', 'local': 22.8, 'comment': 'Valutazione sintetica su Dominican Republic', 'source': 'https://example.com/do'},
    "DZ": {'name': 'Algeria', 'local': 20.3, 'comment': 'Valutazione sintetica su Algeria', 'source': 'https://example.com/dz'},
    "EC": {'name': 'Ecuador', 'local': 20.4, 'comment': 'Valutazione sintetica su Ecuador', 'source': 'https://example.com/ec'},
    "EG": {'name': 'Egypt', 'local': 21.2, 'comment': 'Valutazione sintetica su Egypt', 'source': 'https://example.com/eg'},
    "ER": {'name': 'Eritrea', 'local': 22.8, 'comment': 'Valutazione sintetica su Eritrea', 'source': 'https://example.com/er'},
    "EH": {'name': 'Western Sahara', 'local': 18.0, 'comment': 'Valutazione sintetica su Western Sahara', 'source': 'https://example.com/eh'},
    "ES": {'name': 'Spain', 'local': 18.1, 'comment': 'Valutazione sintetica su Spain', 'source': 'https://example.com/es'},
    "EE": {'name': 'Estonia', 'local': 20.7, 'comment': 'Valutazione sintetica su Estonia', 'source': 'https://example.com/ee'},
    "ET": {'name': 'Ethiopia', 'local': 23.0, 'comment': 'Valutazione sintetica su Ethiopia', 'source': 'https://example.com/et'},
    "FI": {'name': 'Finland', 'local': 26.9, 'comment': 'Valutazione sintetica su Finland', 'source': 'https://example.com/fi'},
    "FJ": {'name': 'Fiji', 'local': 26.8, 'comment': 'Valutazione sintetica su Fiji', 'source': 'https://example.com/fj'},
    "FK": {'name': 'Falkland Islands (Malvinas)', 'local': 23.3, 'comment': 'Valutazione sintetica su Falkland Islands (Malvinas)', 'source': 'https://example.com/fk'},
    "FO": {'name': 'Faroe Islands', 'local': 25.8, 'comment': 'Valutazione sintetica su Faroe Islands', 'source': 'https://example.com/fo'},
    "FM": {'name': 'Micronesia, Federated States of', 'local': 22.0, 'comment': 'Valutazione sintetica su Micronesia, Federated States of', 'source': 'https://example.com/fm'},
    "GA": {'name': 'Gabon', 'local': 24.7, 'comment': 'Valutazione sintetica su Gabon', 'source': 'https://example.com/ga'},
    "GB": {'name': 'United Kingdom', 'local': 23.9, 'comment': 'Valutazione sintetica su United Kingdom', 'source': 'https://example.com/gb'},
    "GE": {'name': 'Georgia', 'local': 26.0, 'comment': 'Valutazione sintetica su Georgia', 'source': 'https://example.com/ge'},
    "GG": {'name': 'Guernsey', 'local': 26.7, 'comment': 'Valutazione sintetica su Guernsey', 'source': 'https://example.com/gg'},
    "GH": {'name': 'Ghana', 'local': 21.2, 'comment': 'Valutazione sintetica su Ghana', 'source': 'https://example.com/gh'},
    "GI": {'name': 'Gibraltar', 'local': 24.0, 'comment': 'Valutazione sintetica su Gibraltar', 'source': 'https://example.com/gi'},
    "GN": {'name': 'Guinea', 'local': 25.9, 'comment': 'Valutazione sintetica su Guinea', 'source': 'https://example.com/gn'},
    "GP": {'name': 'Guadeloupe', 'local': 24.3, 'comment': 'Valutazione sintetica su Guadeloupe', 'source': 'https://example.com/gp'},
    "GM": {'name': 'Gambia', 'local': 20.0, 'comment': 'Valutazione sintetica su Gambia', 'source': 'https://example.com/gm'},
    "GW": {'name': 'Guinea-Bissau', 'local': 25.0, 'comment': 'Valutazione sintetica su Guinea-Bissau', 'source': 'https://example.com/gw'},
    "GQ": {'name': 'Equatorial Guinea', 'local': 26.7, 'comment': 'Valutazione sintetica su Equatorial Guinea', 'source': 'https://example.com/gq'},
    "GR": {'name': 'Greece', 'local': 26.6, 'comment': 'Valutazione sintetica su Greece', 'source': 'https://example.com/gr'},
    "GD": {'name': 'Grenada', 'local': 24.4, 'comment': 'Valutazione sintetica su Grenada', 'source': 'https://example.com/gd'},
    "GL": {'name': 'Greenland', 'local': 19.9, 'comment': 'Valutazione sintetica su Greenland', 'source': 'https://example.com/gl'},
    "GT": {'name': 'Guatemala', 'local': 25.5, 'comment': 'Valutazione sintetica su Guatemala', 'source': 'https://example.com/gt'},
    "GF": {'name': 'French Guiana', 'local': 21.0, 'comment': 'Valutazione sintetica su French Guiana', 'source': 'https://example.com/gf'},
    "GU": {'name': 'Guam', 'local': 24.4, 'comment': 'Valutazione sintetica su Guam', 'source': 'https://example.com/gu'},
    "GY": {'name': 'Guyana', 'local': 20.7, 'comment': 'Valutazione sintetica su Guyana', 'source': 'https://example.com/gy'},
    "HK": {'name': 'Hong Kong', 'local': 22.2, 'comment': 'Valutazione sintetica su Hong Kong', 'source': 'https://example.com/hk'},
    "HM": {'name': 'Heard Island and McDonald Islands', 'local': 25.9, 'comment': 'Valutazione sintetica su Heard Island and McDonald Islands', 'source': 'https://example.com/hm'},
    "HN": {'name': 'Honduras', 'local': 24.0, 'comment': 'Valutazione sintetica su Honduras', 'source': 'https://example.com/hn'},
    "HR": {'name': 'Croatia', 'local': 23.6, 'comment': 'Valutazione sintetica su Croatia', 'source': 'https://example.com/hr'},
    "HT": {'name': 'Haiti', 'local': 26.6, 'comment': 'Valutazione sintetica su Haiti', 'source': 'https://example.com/ht'},
    "HU": {'name': 'Hungary', 'local': 23.0, 'comment': 'Valutazione sintetica su Hungary', 'source': 'https://example.com/hu'},
    "ID": {'name': 'Indonesia', 'local': 18.2, 'comment': 'Valutazione sintetica su Indonesia', 'source': 'https://example.com/id'},
    "IM": {'name': 'Isle of Man', 'local': 19.7, 'comment': 'Valutazione sintetica su Isle of Man', 'source': 'https://example.com/im'},
    "IO": {'name': 'British Indian Ocean Territory', 'local': 24.1, 'comment': 'Valutazione sintetica su British Indian Ocean Territory', 'source': 'https://example.com/io'},
    "IE": {'name': 'Ireland', 'local': 23.5, 'comment': 'Valutazione sintetica su Ireland', 'source': 'https://example.com/ie'},
    "IR": {'name': 'Iran, Islamic Republic of', 'local': 26.3, 'comment': 'Valutazione sintetica su Iran, Islamic Republic of', 'source': 'https://example.com/ir'},
    "IQ": {'name': 'Iraq', 'local': 23.5, 'comment': 'Valutazione sintetica su Iraq', 'source': 'https://example.com/iq'},
    "IS": {'name': 'Iceland', 'local': 26.0, 'comment': 'Valutazione sintetica su Iceland', 'source': 'https://example.com/is'},
    "IL": {'name': 'Israel', 'local': 26.3, 'comment': 'Valutazione sintetica su Israel', 'source': 'https://example.com/il'},
    "JM": {'name': 'Jamaica', 'local': 26.1, 'comment': 'Valutazione sintetica su Jamaica', 'source': 'https://example.com/jm'},
    "JE": {'name': 'Jersey', 'local': 19.8, 'comment': 'Valutazione sintetica su Jersey', 'source': 'https://example.com/je'},
    "JO": {'name': 'Jordan', 'local': 23.7, 'comment': 'Valutazione sintetica su Jordan', 'source': 'https://example.com/jo'},
    "KZ": {'name': 'Kazakhstan', 'local': 25.0, 'comment': 'Valutazione sintetica su Kazakhstan', 'source': 'https://example.com/kz'},
    "KE": {'name': 'Kenya', 'local': 20.4, 'comment': 'Valutazione sintetica su Kenya', 'source': 'https://example.com/ke'},
    "KG": {'name': 'Kyrgyzstan', 'local': 18.1, 'comment': 'Valutazione sintetica su Kyrgyzstan', 'source': 'https://example.com/kg'},
    "KH": {'name': 'Cambodia', 'local': 19.0, 'comment': 'Valutazione sintetica su Cambodia', 'source': 'https://example.com/kh'},
    "KI": {'name': 'Kiribati', 'local': 26.8, 'comment': 'Valutazione sintetica su Kiribati', 'source': 'https://example.com/ki'},
    "KN": {'name': 'Saint Kitts and Nevis', 'local': 21.3, 'comment': 'Valutazione sintetica su Saint Kitts and Nevis', 'source': 'https://example.com/kn'},
    "KR": {'name': 'Korea, Republic of', 'local': 23.3, 'comment': 'Valutazione sintetica su Korea, Republic of', 'source': 'https://example.com/kr'},
    "KW": {'name': 'Kuwait', 'local': 20.3, 'comment': 'Valutazione sintetica su Kuwait', 'source': 'https://example.com/kw'},
    "LA": {'name': "Lao People's Democratic Republic", 'local': 25.2, 'comment': "Valutazione sintetica su Lao People's Democratic Republic", 'source': 'https://example.com/la'},
    "LB": {'name': 'Lebanon', 'local': 18.2, 'comment': 'Valutazione sintetica su Lebanon', 'source': 'https://example.com/lb'},
    "LR": {'name': 'Liberia', 'local': 20.6, 'comment': 'Valutazione sintetica su Liberia', 'source': 'https://example.com/lr'},
    "LY": {'name': 'Libya', 'local': 23.7, 'comment': 'Valutazione sintetica su Libya', 'source': 'https://example.com/ly'},
    "LC": {'name': 'Saint Lucia', 'local': 21.5, 'comment': 'Valutazione sintetica su Saint Lucia', 'source': 'https://example.com/lc'},
    "LI": {'name': 'Liechtenstein', 'local': 26.2, 'comment': 'Valutazione sintetica su Liechtenstein', 'source': 'https://example.com/li'},
    "LK": {'name': 'Sri Lanka', 'local': 22.9, 'comment': 'Valutazione sintetica su Sri Lanka', 'source': 'https://example.com/lk'},
    "LS": {'name': 'Lesotho', 'local': 20.2, 'comment': 'Valutazione sintetica su Lesotho', 'source': 'https://example.com/ls'},
    "LT": {'name': 'Lithuania', 'local': 19.1, 'comment': 'Valutazione sintetica su Lithuania', 'source': 'https://example.com/lt'},
    "LU": {'name': 'Luxembourg', 'local': 25.0, 'comment': 'Valutazione sintetica su Luxembourg', 'source': 'https://example.com/lu'},
    "LV": {'name': 'Latvia', 'local': 26.0, 'comment': 'Valutazione sintetica su Latvia', 'source': 'https://example.com/lv'},
    "MO": {'name': 'Macao', 'local': 21.8, 'comment': 'Valutazione sintetica su Macao', 'source': 'https://example.com/mo'},
    "MF": {'name': 'Saint Martin (French part)', 'local': 26.0, 'comment': 'Valutazione sintetica su Saint Martin (French part)', 'source': 'https://example.com/mf'},
    "MA": {'name': 'Morocco', 'local': 18.9, 'comment': 'Valutazione sintetica su Morocco', 'source': 'https://example.com/ma'},
    "MC": {'name': 'Monaco', 'local': 20.0, 'comment': 'Valutazione sintetica su Monaco', 'source': 'https://example.com/mc'},
    "MD": {'name': 'Moldova, Republic of', 'local': 26.7, 'comment': 'Valutazione sintetica su Moldova, Republic of', 'source': 'https://example.com/md'},
    "MG": {'name': 'Madagascar', 'local': 18.3, 'comment': 'Valutazione sintetica su Madagascar', 'source': 'https://example.com/mg'},
    "MV": {'name': 'Maldives', 'local': 26.7, 'comment': 'Valutazione sintetica su Maldives', 'source': 'https://example.com/mv'},
    "MX": {'name': 'Mexico', 'local': 19.8, 'comment': 'Valutazione sintetica su Mexico', 'source': 'https://example.com/mx'},
    "MH": {'name': 'Marshall Islands', 'local': 24.7, 'comment': 'Valutazione sintetica su Marshall Islands', 'source': 'https://example.com/mh'},
    "MK": {'name': 'North Macedonia', 'local': 23.4, 'comment': 'Valutazione sintetica su North Macedonia', 'source': 'https://example.com/mk'},
    "ML": {'name': 'Mali', 'local': 22.9, 'comment': 'Valutazione sintetica su Mali', 'source': 'https://example.com/ml'},
    "MT": {'name': 'Malta', 'local': 18.2, 'comment': 'Valutazione sintetica su Malta', 'source': 'https://example.com/mt'},
    "MM": {'name': 'Myanmar', 'local': 18.5, 'comment': 'Valutazione sintetica su Myanmar', 'source': 'https://example.com/mm'},
    "ME": {'name': 'Montenegro', 'local': 22.6, 'comment': 'Valutazione sintetica su Montenegro', 'source': 'https://example.com/me'},
    "MN": {'name': 'Mongolia', 'local': 26.6, 'comment': 'Valutazione sintetica su Mongolia', 'source': 'https://example.com/mn'},
    "MP": {'name': 'Northern Mariana Islands', 'local': 26.6, 'comment': 'Valutazione sintetica su Northern Mariana Islands', 'source': 'https://example.com/mp'},
    "MZ": {'name': 'Mozambique', 'local': 19.9, 'comment': 'Valutazione sintetica su Mozambique', 'source': 'https://example.com/mz'},
    "MR": {'name': 'Mauritania', 'local': 20.6, 'comment': 'Valutazione sintetica su Mauritania', 'source': 'https://example.com/mr'},
    "MS": {'name': 'Montserrat', 'local': 18.9, 'comment': 'Valutazione sintetica su Montserrat', 'source': 'https://example.com/ms'},
    "MQ": {'name': 'Martinique', 'local': 23.5, 'comment': 'Valutazione sintetica su Martinique', 'source': 'https://example.com/mq'},
    "MU": {'name': 'Mauritius', 'local': 19.0, 'comment': 'Valutazione sintetica su Mauritius', 'source': 'https://example.com/mu'},
    "MW": {'name': 'Malawi', 'local': 22.1, 'comment': 'Valutazione sintetica su Malawi', 'source': 'https://example.com/mw'},
    "MY": {'name': 'Malaysia', 'local': 26.6, 'comment': 'Valutazione sintetica su Malaysia', 'source': 'https://example.com/my'},
    "YT": {'name': 'Mayotte', 'local': 19.3, 'comment': 'Valutazione sintetica su Mayotte', 'source': 'https://example.com/yt'},
    "NA": {'name': 'Namibia', 'local': 20.9, 'comment': 'Valutazione sintetica su Namibia', 'source': 'https://example.com/na'},
    "NC": {'name': 'New Caledonia', 'local': 25.4, 'comment': 'Valutazione sintetica su New Caledonia', 'source': 'https://example.com/nc'},
    "NE": {'name': 'Niger', 'local': 26.6, 'comment': 'Valutazione sintetica su Niger', 'source': 'https://example.com/ne'},
    "NF": {'name': 'Norfolk Island', 'local': 18.3, 'comment': 'Valutazione sintetica su Norfolk Island', 'source': 'https://example.com/nf'},
    "NI": {'name': 'Nicaragua', 'local': 26.0, 'comment': 'Valutazione sintetica su Nicaragua', 'source': 'https://example.com/ni'},
    "NU": {'name': 'Niue', 'local': 23.8, 'comment': 'Valutazione sintetica su Niue', 'source': 'https://example.com/nu'},
    "NL": {'name': 'Netherlands', 'local': 19.5, 'comment': 'Valutazione sintetica su Netherlands', 'source': 'https://example.com/nl'},
    "NO": {'name': 'Norway', 'local': 24.8, 'comment': 'Valutazione sintetica su Norway', 'source': 'https://example.com/no'},
    "NP": {'name': 'Nepal', 'local': 22.1, 'comment': 'Valutazione sintetica su Nepal', 'source': 'https://example.com/np'},
    "NR": {'name': 'Nauru', 'local': 20.4, 'comment': 'Valutazione sintetica su Nauru', 'source': 'https://example.com/nr'},
    "NZ": {'name': 'New Zealand', 'local': 20.3, 'comment': 'Valutazione sintetica su New Zealand', 'source': 'https://example.com/nz'},
    "OM": {'name': 'Oman', 'local': 21.5, 'comment': 'Valutazione sintetica su Oman', 'source': 'https://example.com/om'},
    "PK": {'name': 'Pakistan', 'local': 26.7, 'comment': 'Valutazione sintetica su Pakistan', 'source': 'https://example.com/pk'},
    "PA": {'name': 'Panama', 'local': 22.8, 'comment': 'Valutazione sintetica su Panama', 'source': 'https://example.com/pa'},
    "PN": {'name': 'Pitcairn', 'local': 21.6, 'comment': 'Valutazione sintetica su Pitcairn', 'source': 'https://example.com/pn'},
    "PE": {'name': 'Peru', 'local': 26.6, 'comment': 'Valutazione sintetica su Peru', 'source': 'https://example.com/pe'},
    "PH": {'name': 'Philippines', 'local': 25.1, 'comment': 'Valutazione sintetica su Philippines', 'source': 'https://example.com/ph'},
    "PW": {'name': 'Palau', 'local': 21.7, 'comment': 'Valutazione sintetica su Palau', 'source': 'https://example.com/pw'},
    "PG": {'name': 'Papua New Guinea', 'local': 18.5, 'comment': 'Valutazione sintetica su Papua New Guinea', 'source': 'https://example.com/pg'},
    "PL": {'name': 'Poland', 'local': 20.7, 'comment': 'Valutazione sintetica su Poland', 'source': 'https://example.com/pl'},
    "PR": {'name': 'Puerto Rico', 'local': 21.2, 'comment': 'Valutazione sintetica su Puerto Rico', 'source': 'https://example.com/pr'},
    "KP": {'name': "Korea, Democratic People's Republic of", 'local': 20.2, 'comment': "Valutazione sintetica su Korea, Democratic People's Republic of", 'source': 'https://example.com/kp'},
    "PT": {'name': 'Portugal', 'local': 21.1, 'comment': 'Valutazione sintetica su Portugal', 'source': 'https://example.com/pt'},
    "PY": {'name': 'Paraguay', 'local': 26.2, 'comment': 'Valutazione sintetica su Paraguay', 'source': 'https://example.com/py'},
    "PS": {'name': 'Palestine, State of', 'local': 23.5, 'comment': 'Valutazione sintetica su Palestine, State of', 'source': 'https://example.com/ps'},
    "PF": {'name': 'French Polynesia', 'local': 18.9, 'comment': 'Valutazione sintetica su French Polynesia', 'source': 'https://example.com/pf'},
    "QA": {'name': 'Qatar', 'local': 25.1, 'comment': 'Valutazione sintetica su Qatar', 'source': 'https://example.com/qa'},
    "RE": {'name': 'Réunion', 'local': 18.9, 'comment': 'Valutazione sintetica su Réunion', 'source': 'https://example.com/re'},
    "RO": {'name': 'Romania', 'local': 21.9, 'comment': 'Valutazione sintetica su Romania', 'source': 'https://example.com/ro'},
  }
};